"use client";
import React, { useEffect, useState } from "react";
import { api, getImageUrl } from "@/lib/api";

export default function Gallery() {
    const [images, setImages] = useState([]);
    const [loading, setLoading] = useState(true);

    const fetchGallery = () => {
        api.getGallery()
            .then(setImages)
            .catch(console.error)
            .finally(() => setLoading(false));
    };

    useEffect(() => {
        fetchGallery();

        window.addEventListener("chatDeleted", fetchGallery);
        return () => window.removeEventListener("chatDeleted", fetchGallery);
    }, []);

    if (loading) return <div className="pitch-black-bg" style={{ padding: "40px", textAlign: "center", color: "#666" }}>Loading gallery...</div>;

    return (
        <div className="pitch-black-bg animate-fade-in" style={{ padding: "40px" }}>
            <div style={{ marginBottom: "40px" }}>
                <h2 style={{ fontSize: "32px", fontWeight: "800", marginBottom: "10px" }}>Community Creations</h2>
                <p style={{ color: "var(--text-muted)" }}>Explore images generated by your local Flux.1 model.</p>
            </div>

            <div style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
                gap: "20px"
            }}>
                {images.length === 0 ? (
                    <div style={{ gridColumn: "1 / -1", textAlign: "center", padding: "100px", border: "1px dashed var(--border)", borderRadius: "16px" }}>
                        <p style={{ color: "var(--text-muted)" }}>No images generated yet. Start a chat to create one!</p>
                    </div>
                ) : images.map(img => (
                    <div key={img.id} className="glass-morphism" style={{
                        borderRadius: "16px",
                        overflow: "hidden",
                        transition: "transform 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275)"
                    }} onMouseEnter={(e) => e.currentTarget.style.transform = "scale(1.02)"}
                        onMouseLeave={(e) => e.currentTarget.style.transform = "scale(1)"}>
                        <div style={{ position: "relative", paddingTop: "100%" }}>
                            <img
                                src={getImageUrl(img.url)}
                                alt={img.prompt}
                                style={{ position: "absolute", top: 0, left: 0, width: "100%", height: "100%", objectFit: "cover" }}
                            />
                        </div>
                        <div style={{ padding: "15px" }}>
                            <p style={{ fontSize: "13px", color: "#eee", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" }}>
                                {img.prompt}
                            </p>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
